### ISSUE TITLE
Enhance User Experience By Directly Navigating The User To The Medium Article

### ISSUE THREAD

**Issue by Zujaj** [bxcodec/github-readme-medium-recent-article#15]
# Expected Behavior

1. A user clicks on the Medium article box.
2. He gets navigated to that Medium article directly.

# Current Behavior

1. A user clicks on the Medium article box.
2. He navigates to a new page & again clicks on the Medium article box.
3. The Medium article gets opened in a new tab.

![Bad User Experience](https://user-images.githubusercontent.com/46039324/200547425-dbaac7aa-29be-4538-95db-3c3d9a3ab2eb.png)

https://user-images.githubusercontent.com/46039324/200548485-481cd9e7-5632-44f5-a94a-6ecf0b8c62f3.mp4

Can this be resolved? It happens frequently and is not a good approach for a better user experience.

**Comment by amartyanambiar** [comment]
I am not able to reproduce this behaviour. Checked your Github landing page too. (works fine)
I believe this issue can be closed.
