### ISSUE TITLE
Blog post is not showing on the profile

### ISSUE THREAD

**Issue by sailohitaksh-cryptic** [bxcodec/github-readme-medium-recent-article#16]
![image](https://github.com/bxcodec/github-readme-medium-recent-article/assets/74712527/3a9d795e-5d3a-43f7-8daa-1eed68adf532)

<a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@rainasai603/0"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@rainasai603/0" alt="Recent article #1"></a>

whenever i am trying to add the blog it is showing in the following way. 

Please help me

**Comment by gisynw** [comment]
I have the same issue as @sailohitaksh-cryptic , any solution to this? Thank you in advance for any help.

**Comment by gisynw** [comment]
> 



> I have the same issue as @sailohitaksh-cryptic , any solution to this? Thank you in advance for any help.
when I use index = 0 or 1  (I have two posts on Medium), the image can show, but the link is not accessible and show the error message: This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cle1::txcth-1690594246972-3a7af17fa0e2.
Thank you for any help.

**Comment by gisynw** [comment]
I found this one is working. 
<a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@your suer name/0"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@your user name/0" alt="Recent Article 0"></a>

**Comment by lmn0** [comment]
@gisynw looks like this is working for you now. Did you make any changes?

**Comment by bxcodec** [comment]
fixed in the latest changes #22 
can re-open if still happening
