### ISSUE TITLE
the link doesnt work for all the articles

### ISSUE THREAD

**Issue by sidsanc** [bxcodec/github-readme-medium-recent-article#17]
The script <a target="_blank" href="https://github-readme-medium-recent-article.vercel.app/medium/@username/index"><img src="https://github-readme-medium-recent-article.vercel.app/medium/@username/index" alt="Recent Article index">
surprisingly only works with index=0 i.e. the latest article. its not working with other indices. please help!

**Comment by bxcodec** [comment]
fixed in the latest changes #22 
can re-open if still happening
